### ISSUE TITLE
License

### ISSUE THREAD

**Issue by donatoaz** [feelfreelinux/ds18b20#3]
Hi, first off, thanks for the work. Much appreciated.

I have used your library on an open source project and before I post it to github I would like to know what is the license.

best regards,

**Comment by feelfreelinux** [comment]
@donatoaz Thanks for using my library! I've added MIT license text, hope it suits you :)

**Comment by donatoaz** [comment]
Great! Faster than the spanish inquisition.....

[mruby-esp32-ds18b20](https://github.com/donatoaz/mruby-esp32-ds18b20)
